language: go

go:
  - 1.8.x
  - 1.9.x

before_install:
  - wget "https://github.com/Masterminds/glide/releases/download/v0.13.1/glide-v0.13.1-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-v0.13.1-linux-amd64.tar.gz
  - export PATH="$HOME/bin:$PATH"

install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - go get -u github.com/golang/lint/golint
  - go get github.com/axw/gocov/gocov
  - glide install

before_script:
  - ./cc-test-reporter before-build

script:
  - golint `go list ./... | grep -v /vendor/`
  - |
    for pkg in $(go list ./... | grep -v vendor); do
        go test -coverprofile=$(echo $pkg | tr / -).cover $pkg
    done
  - >-
    echo "mode: set" > c.out
  - grep -h -v "^mode:" ./*.cover >> c.out
  - rm -f *.cover
  - go build

after_script:
  - ./cc-test-reporter after-build -t gocov --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
