// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/message.proto

/*
Package proto is a generated protocol buffer package.

protoc --go_out=plugins=grpc:. proto/*.proto

It is generated from these files:
	proto/message.proto

It has these top-level messages:
	AuthRequest
	AuthResponse
	Empty
	TaskDone
	TaskPublish
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthRequest struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *AuthRequest) Reset()                    { *m = AuthRequest{} }
func (m *AuthRequest) String() string            { return proto1.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()               {}
func (*AuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AuthRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthResponse struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *AuthResponse) Reset()                    { *m = AuthResponse{} }
func (m *AuthResponse) String() string            { return proto1.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()               {}
func (*AuthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type TaskDone struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Data string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	Time string `protobuf:"bytes,4,opt,name=time" json:"time,omitempty"`
}

func (m *TaskDone) Reset()                    { *m = TaskDone{} }
func (m *TaskDone) String() string            { return proto1.CompactTextString(m) }
func (*TaskDone) ProtoMessage()               {}
func (*TaskDone) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TaskDone) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskDone) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaskDone) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *TaskDone) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type TaskPublish struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Data string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	Time string `protobuf:"bytes,4,opt,name=time" json:"time,omitempty"`
	Ttl  uint32 `protobuf:"varint,5,opt,name=ttl" json:"ttl,omitempty"`
}

func (m *TaskPublish) Reset()                    { *m = TaskPublish{} }
func (m *TaskPublish) String() string            { return proto1.CompactTextString(m) }
func (*TaskPublish) ProtoMessage()               {}
func (*TaskPublish) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TaskPublish) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskPublish) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaskPublish) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *TaskPublish) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *TaskPublish) GetTtl() uint32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func init() {
	proto1.RegisterType((*AuthRequest)(nil), "proto.AuthRequest")
	proto1.RegisterType((*AuthResponse)(nil), "proto.AuthResponse")
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
	proto1.RegisterType((*TaskDone)(nil), "proto.TaskDone")
	proto1.RegisterType((*TaskPublish)(nil), "proto.TaskPublish")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Message service

type MessageClient interface {
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Done(ctx context.Context, in *TaskDone, opts ...grpc.CallOption) (*Empty, error)
	Register(ctx context.Context, opts ...grpc.CallOption) (Message_RegisterClient, error)
}

type messageClient struct {
	cc *grpc.ClientConn
}

func NewMessageClient(cc *grpc.ClientConn) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/proto.Message/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) Done(ctx context.Context, in *TaskDone, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.Message/Done", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) Register(ctx context.Context, opts ...grpc.CallOption) (Message_RegisterClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Message_serviceDesc.Streams[0], c.cc, "/proto.Message/Register", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageRegisterClient{stream}
	return x, nil
}

type Message_RegisterClient interface {
	Send(*Empty) error
	Recv() (*TaskPublish, error)
	grpc.ClientStream
}

type messageRegisterClient struct {
	grpc.ClientStream
}

func (x *messageRegisterClient) Send(m *Empty) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageRegisterClient) Recv() (*TaskPublish, error) {
	m := new(TaskPublish)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Message service

type MessageServer interface {
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
	Done(context.Context, *TaskDone) (*Empty, error)
	Register(Message_RegisterServer) error
}

func RegisterMessageServer(s *grpc.Server, srv MessageServer) {
	s.RegisterService(&_Message_serviceDesc, srv)
}

func _Message_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Message/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_Done_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskDone)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).Done(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Message/Done",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).Done(ctx, req.(*TaskDone))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageServer).Register(&messageRegisterServer{stream})
}

type Message_RegisterServer interface {
	Send(*TaskPublish) error
	Recv() (*Empty, error)
	grpc.ServerStream
}

type messageRegisterServer struct {
	grpc.ServerStream
}

func (x *messageRegisterServer) Send(m *TaskPublish) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageRegisterServer) Recv() (*Empty, error) {
	m := new(Empty)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Message_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Message",
	HandlerType: (*MessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _Message_Auth_Handler,
		},
		{
			MethodName: "Done",
			Handler:    _Message_Done_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _Message_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/message.proto",
}

func init() { proto1.RegisterFile("proto/message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x90, 0x4b, 0x4b, 0xc3, 0x40,
	0x14, 0x85, 0x99, 0x34, 0xb1, 0xf5, 0xb6, 0x3e, 0xb8, 0x75, 0x11, 0xba, 0x2a, 0x41, 0x21, 0xab,
	0xb6, 0xe8, 0xc2, 0xb5, 0xa0, 0x4b, 0x41, 0x82, 0xb8, 0x9f, 0x92, 0x4b, 0x3b, 0xa4, 0xc9, 0xc4,
	0xce, 0xcd, 0xc2, 0xdf, 0xe1, 0x1f, 0x96, 0x79, 0x28, 0xd3, 0xbd, 0xab, 0x39, 0xf3, 0xdd, 0x17,
	0xe7, 0xc0, 0xbc, 0x3f, 0x6a, 0xd6, 0xeb, 0x96, 0x8c, 0x91, 0x3b, 0x5a, 0xb9, 0x1f, 0x66, 0xee,
	0x29, 0x1e, 0x61, 0xfa, 0x34, 0xf0, 0xbe, 0xa2, 0xcf, 0x81, 0x0c, 0x23, 0x42, 0xda, 0xc9, 0x96,
	0x72, 0xb1, 0x14, 0xe5, 0x79, 0xe5, 0x34, 0xde, 0x40, 0xc6, 0xba, 0xa1, 0x2e, 0x4f, 0x1c, 0xf4,
	0x9f, 0xe2, 0x16, 0x66, 0x7e, 0xd0, 0xf4, 0xba, 0x33, 0x51, 0x97, 0x88, 0xbb, 0xc6, 0x90, 0xbd,
	0xb4, 0x3d, 0x7f, 0x15, 0x1f, 0x30, 0x79, 0x97, 0xa6, 0x79, 0xd6, 0x1d, 0xe1, 0x25, 0x24, 0xaa,
	0x0e, 0x7d, 0x89, 0xaa, 0xff, 0x8e, 0x26, 0xd1, 0x51, 0x84, 0xb4, 0x96, 0x2c, 0xf3, 0x91, 0x67,
	0x56, 0x5b, 0xc6, 0xaa, 0xa5, 0x3c, 0xf5, 0xcc, 0xea, 0xa2, 0x81, 0xa9, 0xdd, 0xfb, 0x36, 0x6c,
	0x0f, 0xca, 0xec, 0xff, 0x73, 0x35, 0x5e, 0xc3, 0x88, 0xf9, 0x90, 0x67, 0x4b, 0x51, 0x5e, 0x54,
	0x56, 0xde, 0x7f, 0x0b, 0x18, 0xbf, 0xfa, 0x14, 0x71, 0x0d, 0xa9, 0xf5, 0x8f, 0xe8, 0xf3, 0x5c,
	0x45, 0x29, 0x2e, 0xe6, 0x27, 0x2c, 0x04, 0x74, 0x07, 0xa9, 0x73, 0x7f, 0x15, 0x8a, 0xbf, 0x71,
	0x2c, 0x66, 0x01, 0xb8, 0xa0, 0x70, 0x03, 0x93, 0x8a, 0x76, 0xca, 0x30, 0x1d, 0xf1, 0xa4, 0xb2,
	0xc0, 0x68, 0x30, 0xf8, 0x2d, 0xc5, 0x46, 0x6c, 0xcf, 0x1c, 0x7e, 0xf8, 0x09, 0x00, 0x00, 0xff,
	0xff, 0xfa, 0xfe, 0xde, 0xd9, 0xe7, 0x01, 0x00, 0x00,
}
