# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "TaskDone" do
    optional :id, :string, 1
    optional :name, :string, 2
    optional :data, :string, 3
    optional :time, :string, 4
  end
  add_message "TaskPublish" do
    optional :id, :string, 1
    optional :name, :string, 2
    optional :data, :string, 3
    optional :time, :string, 4
    optional :ttl, :uint32, 5
  end
end

TaskDone = Google::Protobuf::DescriptorPool.generated_pool.lookup("TaskDone").msgclass
TaskPublish = Google::Protobuf::DescriptorPool.generated_pool.lookup("TaskPublish").msgclass
